# Generated by Django 5.2.7 on 2025-11-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('api_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_api_id', models.IntegerField()),
                ('team_name', models.CharField(default='', max_length=100)),
                ('team_abbreviation', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
