# Generated by Django 5.2.7 on 2025-11-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2hapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_abbreviation',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
